export const AUTH_LOADING = "AUTH_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const USER_ERROR = "USER_ERROR";
export const LOGOUT = "LOGOUT";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_REMOVE = "USER_PROFILE_REMOVE";
export const USER_PROFILE_CREATED = "USER_PROFILE_CREATED";
export const USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED";
export const USER_DELETED = "USER_DELETED";

export const PROFILES_LOADED = "PROFILES_LOADED";
export const USER_REPOS_LOADED = "USER_REPOS_LOADED";
