export const AUTH_LOADING = "AUTH_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const USER_ERROR = "USER_ERROR";
export const LOGOUT = "LOGOUT";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_REMOVE = "USER_PROFILE_REMOVE";
export const USER_PROFILE_CREATED = "USER_PROFILE_CREATED";
export const USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED";
export const USER_DELETED = "USER_DELETED";

export const PROFILES_LOADED = "PROFILES_LOADED";
export const USER_REPOS_LOADED = "USER_REPOS_LOADED";

export const POST_CREATED = "POST_CREATED";
export const POST_DELETED = "POST_DELETED";
export const POST_LIKES_UPDATED = "POST_LIKES_UPDATED";
export const POST_LOADED = "POST_LOADED";

export const POSTS_ERROR = "POSTS_ERROR";
export const POSTS_LOADED = "POSTS_LOADED";
export const POSTS_LOADING = "POSTS_LOADING";

export const COMMENT_CREATED = "COMMENT_CREATED";
export const COMMENT_DELETED = "COMMENT_DELETED";
